# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='createdby',
        ),
    ]
