# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0003_register_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_name',
            field=models.CharField(blank=True, default=' ', max_length=80, null=True),
        ),
    ]
