# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0004_category_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='start_date',
            new_name='date',
        ),
    ]
