# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0005_usertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
