# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ce_availability', '0005_auto_20180305_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='manager',
            field=models.ForeignKey(blank=True, default=6, on_delete=django.db.models.deletion.CASCADE, related_name='LocManager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='register',
            name='hours',
            field=models.FloatField(blank=True),
        ),
    ]
