# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0006_auto_20180611_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__last_name']},
        ),
    ]
