# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0007_auto_20181023_0443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__last_name', 'location']},
        ),
    ]
