# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0008_auto_20181023_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['location', 'user__last_name']},
        ),
    ]
