# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0009_auto_20171206_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='comments',
            field=models.CharField(blank=True, max_length=41),
        ),
    ]
