# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0009_auto_20181023_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='loc_short',
            field=models.CharField(default=' ', max_length=3),
        ),
    ]
