# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-17 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0011_employee_tele_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='enc_pass',
            field=models.BinaryField(blank=True),
        ),
    ]
