# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0012_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailability',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='ce_availability.Category'),
            preserve_default=False,
        ),
    ]
