# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0014_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location', to='ce_availability.Location'),
        ),
    ]
