# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0015_auto_20180123_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='KindOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindofday', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='kindofday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KindOfDay', to='ce_availability.KindOfDay'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loc', to='ce_availability.Location'),
        ),
    ]
