# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0017_kindofday_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindofday',
            name='laborablehours',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
