# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0018_kindofday_laborablehours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kindofday',
            name='laborablehours',
        ),
    ]
