# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0003_employee_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='register',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
