# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0007_auto_20171205_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='comments',
            field=models.CharField(max_length=40),
        ),
    ]
