# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0008_auto_20171206_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='hours',
            field=models.FloatField(),
        ),
    ]
