# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0010_auto_20171218_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='end_date',
        ),
    ]
