# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0019_remove_kindofday_laborablehours'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindofday',
            name='laborablehours',
            field=models.FloatField(default=8.5),
            preserve_default=False,
        ),
    ]
