# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0020_kindofday_laborablehours'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='comment',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
