# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0022_register_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='created_by',
            field=models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.CASCADE, related_name='CreatedByUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
