# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ce_availability', '0024_auto_20180220_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreatedByUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
