# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, default=' ', max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='ce_overtime.Category')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterOvertime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_hours', models.FloatField(blank=True)),
                ('work_hours', models.FloatField(blank=True)),
                ('others_hours', models.FloatField(blank=True)),
                ('comments', models.CharField(blank=True, max_length=41)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdbyuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdbyuser', to=settings.AUTH_USER_MODEL)),
                ('overtimereg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Overtime', to='ce_overtime.Overtime')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
