# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce_overtime', '0002_auto_20190520_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='category',
        ),
        migrations.AddField(
            model_name='overtime',
            name='short_name',
            field=models.CharField(blank=True, default=' ', max_length=80, null=True),
        ),
    ]
